# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/codes/vivado/lab_4/lab_4.srcs/sources_1/ip/block_mem/block_mem.xci
# IP: The module: 'block_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/codes/vivado/lab_4/lab_4.gen/sources_1/ip/block_mem/block_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/codes/vivado/lab_4/lab_4.srcs/sources_1/ip/block_mem/block_mem.xci
# IP: The module: 'block_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/codes/vivado/lab_4/lab_4.gen/sources_1/ip/block_mem/block_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
