# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu.xdc

# IP: ip/block_mem1/block_mem1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_mem1 || ORIG_REF_NAME==block_mem1} -quiet] -quiet

# IP: ip/block_mem/block_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_mem || ORIG_REF_NAME==block_mem} -quiet] -quiet

# XDC: d:/codes/vivado/lab_4/lab_4.gen/sources_1/ip/block_mem1/block_mem1_ooc.xdc

# XDC: d:/codes/vivado/lab_4/lab_4.gen/sources_1/ip/block_mem/block_mem_ooc.xdc
