# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/codes/vivado/lab_3/lab_3.srcs/sources_1/ip/block_ram/block_ram.xci
# IP: The module: 'block_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/codes/vivado/lab_3/lab_3.gen/sources_1/ip/block_ram/block_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/codes/vivado/lab_3/lab_3.srcs/sources_1/ip/block_ram/block_ram.xci
# IP: The module: 'block_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/codes/vivado/lab_3/lab_3.gen/sources_1/ip/block_ram/block_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
